### ISSUE TITLE
用Electron运行Leanote桌面

### ISSUE THREAD

**Issue by lealife** [leanote/desktop-app#113]
## 安装Electron
具体安装方法请见 https://github.com/atom/electron#downloads

## 运行Leanote
安装好Electron后, 下载本仓库, 使用 `electron .` 运行Leanote Desktop
```
$> cd PATH_TO_LEANOTE_DESKTOP_APP
$> electron .
```

**Comment by lealife** [comment]
有问题, 请留言

**Comment by nodeman777** [comment]
缺少APP模块诶
```
Error opening app
The app provided is not a valid Electron app, please read the docs on how to write one:
https://github.com/electron/electron/tree/v1.1.0/docs

Error: Cannot find module 'app'
```

**Comment by lealife** [comment]
难道electron更新了?

**Comment by sinodang** [comment]
Error: Cannot find module 'pdf_main'

**Comment by xingstarx** [comment]
一切运行正常吧

**Comment by dean2021** [comment]
TypeError: app.makeSingleInstance is not a function

**Comment by Mrzyxing** [comment]
> TypeError: app.makeSingleInstance is not a function

怎么样，解决了吗？我也是这个问题

**Comment by Mrzyxing** [comment]
nodejs version: v10.15.1
npm version:6.8.0
system version:centos 7.4

```
# error while loading shared libraries: libXss.so.1 while install electron
yum install libXScrnSaver
# latest version 4 will cause electron . throw TypeError: app.makeSingleInstance is not a function
# npm install -g electron will throw Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/electron/.electron'
# add params -unsafe-perm=true and --allow-root
sudo npm install -g electron@3 --unsafe-perm=true --allow-root
```

**Comment by shen-zc** [comment]
electrom@3.1.13

**Comment by shen-zc** [comment]
但我遇到了这个问题：

`Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
Error: Cannot find module 'C:\Users\Andrew\Desktop\leanote-win32-x64\leanote-win32-x64\resources\app\index.js'
    at Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Function.Module._resolveFilename (C:\Users\Andrew\Desktop\leanote-win32-x64\leanote-win32-x64\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (internal/modules/cjs/loader.js:528:25)
    at Object.<anonymous> (C:\Users\Andrew\Desktop\leanote-win32-x64\leanote-win32-x64\resources\electron.asar\browser\init.js:189:8)
    at Object.<anonymous> (C:\Users\Andrew\Desktop\leanote-win32-x64\leanote-win32-x64\resources\electron.asar\browser\init.js:191:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)`

**Comment by killliu** [comment]
> > TypeError: app.makeSingleInstance is not a function
> 
> 怎么样，解决了吗？我也是这个问题

都没人回复啊，同样的问题

**Comment by Evelyn0910** [comment]
> 错误：找不到模块“ pdf_main”

想知道解决了吗。。

**Comment by dean2021** [comment]
> > > TypeError: app.makeSingleInstance is not a function
> > 
> > 
> > 怎么样，解决了吗？我也是这个问题
> 
> 都没人回复啊，同样的问题

没有啊大兄嘚
