### ISSUE TITLE
[BUG] Request error Error: getaddrinfo EAI_AGAIN leanote.com:443

### ISSUE THREAD

**Issue by jsonbruce** [leanote/desktop-app#251]
- 环境
Ubuntu x64
Leanote v2.4

1. 无法同步
```
get Server LastSyncState error!!   /opt/leanote/resources/app/node_modules/sync.js:799 	
(anonymous function)	@	/opt/leanote/resources/app/node_modules/sync.js:799
(anonymous function)	@	/opt/leanote/resources/app/node_modules/api.js:215
done	@	needle.js:223
(anonymous function)	@	needle.js:383
emitOne	@	events.js:96
emit	@	events.js:188
socketErrorListener	@	_http_client.js:306
emitOne	@	events.js:96
emit	@	events.js:188
connectErrorNT	@	net.js:1015
_combinedTickCallback	@	internal/process/next_tick.js:74
_tickCallback	@	internal/process/next_tick.js:98
```

2. 检查更新时出错:
```
Request error Error: getaddrinfo EAI_AGAIN app.leanote.com:80
    at Object.exports._errnoException (util.js:949:11)
    at errnoException (dns.js:33:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:79:26)
```

3. 是旗舰套餐

**Comment by jsonbruce** [comment]
今天已经修复了。

**Comment by jsonbruce** [comment]
今天又坏掉了。。。
